version: 2
jobs:
  build_and_test:
    docker:
      - image: circleci/openjdk:8-jdk
      
    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-

      - setup_remote_docker:
          version: 17.05.0-ce

      - run: 
          name: Download Gcloud
          command: |
            export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
            echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
            sudo apt-get update && sudo apt-get install google-cloud-sdk
            sudo apt-get install google-cloud-sdk-app-engine-java
            gcloud init

      - run: gradle dependencies

      - run: gradle clean build -xtest

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
        
  push_to_gcp:
    docker:
      - image: google/cloud-sdk

    steps:
      - checkout

      - setup_remote_docker:
          version: 17.05.0-ce

      - run: 
          name: Install gradle
          command: |
            wget https://services.gradle.org/distributions/gradle-3.4.1-bin.zip
            sudo mkdir /opt/gradle
            sudo unzip -d /opt/gradle gradle-3.4.1-bin.zip
            export PATH=$PATH:/opt/gradle/gradle-3.4.1/bin
            gradle buildDocker -xtest

      - run: 
          name: Setup Google Cloud SDK
          command: |
            apt-get install -qq -y gettext
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project $GOOGLE_PROJECT_ID
            gcloud --quiet config set compute/zone $GOOGLE_COMPUTE_ZONE
            gcloud components install app-engine-java
      - setup_remote_docker
      - run: 
          name: Docker build and push
          command: |
            gcloud auth configure-docker
            docker push $GOOGLE_CLOUD_RESOURCE/$GOOGLE_PROJECT_ID/$PROJECT_NAME:latest
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build_and_test
      - push_to_gcp:
          requires:
            - build_and_test
          filters:
            branches:
              only: master
